# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'services/gui/resources/ui_interface/buy.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1360, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(0, 380, 268, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_3.sizePolicy().hasHeightForWidth())
        self.button_3.setSizePolicy(sizePolicy)
        self.button_3.setMinimumSize(QtCore.QSize(268, 188))
        self.button_3.setMaximumSize(QtCore.QSize(268, 188))
        self.button_3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.button_3.setFont(font)
        self.button_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 60px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.button_3.setObjectName("button_3")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(0, 190, 268, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_2.sizePolicy().hasHeightForWidth())
        self.button_2.setSizePolicy(sizePolicy)
        self.button_2.setMinimumSize(QtCore.QSize(268, 188))
        self.button_2.setMaximumSize(QtCore.QSize(268, 188))
        self.button_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.button_2.setFont(font)
        self.button_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 60px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.button_2.setObjectName("button_2")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(0, 0, 268, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_1.sizePolicy().hasHeightForWidth())
        self.button_1.setSizePolicy(sizePolicy)
        self.button_1.setMinimumSize(QtCore.QSize(268, 188))
        self.button_1.setMaximumSize(QtCore.QSize(268, 188))
        self.button_1.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.button_1.setFont(font)
        self.button_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 60px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.button_1.setDefault(False)
        self.button_1.setObjectName("button_1")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(0, 570, 268, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_4.sizePolicy().hasHeightForWidth())
        self.button_4.setSizePolicy(sizePolicy)
        self.button_4.setMinimumSize(QtCore.QSize(268, 188))
        self.button_4.setMaximumSize(QtCore.QSize(268, 188))
        self.button_4.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.button_4.setFont(font)
        self.button_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 150, 0);\n"
"border-top-right-radius: 60px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.button_4.setObjectName("button_4")
        self.columnView = QtWidgets.QColumnView(self.centralwidget)
        self.columnView.setGeometry(QtCore.QRect(270, 192, 811, 375))
        self.columnView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.columnView.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 60px;\n"
"border-bottom-right-radius: 60px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.columnView.setObjectName("columnView")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(640, 230, 80, 324))
        self.progressBar.setMinimumSize(QtCore.QSize(80, 324))
        self.progressBar.setMaximumSize(QtCore.QSize(80, 324))
        self.progressBar.setSizeIncrement(QtCore.QSize(80, 324))
        self.progressBar.setBaseSize(QtCore.QSize(80, 324))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progressBar.setFont(font)
        self.progressBar.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.progressBar.setToolTipDuration(6)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 20px;\n"
"    border-color:  rgb(179, 179, 179);\n"
"    color: white;\n"
"    border: 1px solid #B3B3B3;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 20px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0\n"
"rgba(0, 0, 255, 255))\n"
"}\n"
"\n"
"")
        self.progressBar.setProperty("value", 26)
        self.progressBar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.price_1 = QtWidgets.QFrame(self.centralwidget)
        self.price_1.setGeometry(QtCore.QRect(0, 110, 268, 80))
        self.price_1.setMinimumSize(QtCore.QSize(268, 80))
        self.price_1.setMaximumSize(QtCore.QSize(268, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.price_1.setFont(font)
        self.price_1.setMouseTracking(True)
        self.price_1.setTabletTracking(False)
        self.price_1.setAcceptDrops(True)
        self.price_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 255);\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 60px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.price_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_1.setObjectName("price_1")
        self.price_2 = QtWidgets.QFrame(self.centralwidget)
        self.price_2.setGeometry(QtCore.QRect(0, 300, 268, 80))
        self.price_2.setMinimumSize(QtCore.QSize(268, 80))
        self.price_2.setMaximumSize(QtCore.QSize(268, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.price_2.setFont(font)
        self.price_2.setMouseTracking(True)
        self.price_2.setTabletTracking(False)
        self.price_2.setAcceptDrops(True)
        self.price_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 255);\n"
"border-top-right-radius: 60px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.price_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_2.setObjectName("price_2")
        self.price_3 = QtWidgets.QFrame(self.centralwidget)
        self.price_3.setGeometry(QtCore.QRect(0, 490, 268, 80))
        self.price_3.setMinimumSize(QtCore.QSize(268, 80))
        self.price_3.setMaximumSize(QtCore.QSize(268, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.price_3.setFont(font)
        self.price_3.setMouseTracking(True)
        self.price_3.setTabletTracking(False)
        self.price_3.setAcceptDrops(True)
        self.price_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 255);\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 60px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.price_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_3.setObjectName("price_3")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(1085, 190, 268, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_6.sizePolicy().hasHeightForWidth())
        self.button_6.setSizePolicy(sizePolicy)
        self.button_6.setMinimumSize(QtCore.QSize(268, 188))
        self.button_6.setMaximumSize(QtCore.QSize(268, 188))
        self.button_6.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.button_6.setFont(font)
        self.button_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 20px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-right-radius: 60px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.button_6.setObjectName("button_6")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(1085, 380, 268, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_7.sizePolicy().hasHeightForWidth())
        self.button_7.setSizePolicy(sizePolicy)
        self.button_7.setMinimumSize(QtCore.QSize(268, 188))
        self.button_7.setMaximumSize(QtCore.QSize(268, 188))
        self.button_7.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.button_7.setFont(font)
        self.button_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 60px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.button_7.setObjectName("button_7")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(1085, 0, 268, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_5.sizePolicy().hasHeightForWidth())
        self.button_5.setSizePolicy(sizePolicy)
        self.button_5.setMinimumSize(QtCore.QSize(268, 188))
        self.button_5.setMaximumSize(QtCore.QSize(268, 188))
        self.button_5.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.button_5.setFont(font)
        self.button_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 60px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.button_5.setDefault(False)
        self.button_5.setObjectName("button_5")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(1085, 570, 268, 188))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_8.sizePolicy().hasHeightForWidth())
        self.button_8.setSizePolicy(sizePolicy)
        self.button_8.setMinimumSize(QtCore.QSize(268, 188))
        self.button_8.setMaximumSize(QtCore.QSize(268, 188))
        self.button_8.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(10)
        self.button_8.setFont(font)
        self.button_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(224, 30, 0);\n"
"border-top-right-radius: 20px;\n"
"border-bottom-right-radius: 60px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.button_8.setObjectName("button_8")
        self.price_6 = QtWidgets.QFrame(self.centralwidget)
        self.price_6.setGeometry(QtCore.QRect(1085, 490, 268, 80))
        self.price_6.setMinimumSize(QtCore.QSize(268, 80))
        self.price_6.setMaximumSize(QtCore.QSize(268, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.price_6.setFont(font)
        self.price_6.setMouseTracking(True)
        self.price_6.setTabletTracking(False)
        self.price_6.setAcceptDrops(True)
        self.price_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 255);\n"
"border-top-right-radius: 60px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.price_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_6.setObjectName("price_6")
        self.price_4 = QtWidgets.QFrame(self.centralwidget)
        self.price_4.setGeometry(QtCore.QRect(1085, 110, 268, 80))
        self.price_4.setMinimumSize(QtCore.QSize(268, 80))
        self.price_4.setMaximumSize(QtCore.QSize(268, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.price_4.setFont(font)
        self.price_4.setMouseTracking(True)
        self.price_4.setTabletTracking(False)
        self.price_4.setAcceptDrops(True)
        self.price_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 255);\n"
"border-top-right-radius: 60px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.price_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_4.setObjectName("price_4")
        self.price_5 = QtWidgets.QFrame(self.centralwidget)
        self.price_5.setGeometry(QtCore.QRect(1085, 300, 268, 80))
        self.price_5.setMinimumSize(QtCore.QSize(268, 80))
        self.price_5.setMaximumSize(QtCore.QSize(268, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.price_5.setFont(font)
        self.price_5.setMouseTracking(True)
        self.price_5.setTabletTracking(False)
        self.price_5.setAcceptDrops(True)
        self.price_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 255);\n"
"border-top-right-radius: 20px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-right-radius: 60px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.price_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_5.setObjectName("price_5")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(270, 0, 811, 190))
        self.widget.setMinimumSize(QtCore.QSize(811, 190))
        self.widget.setMaximumSize(QtCore.QSize(811, 190))
        self.widget.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 60px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.widget.setObjectName("widget")
        self.price_7 = QtWidgets.QFrame(self.widget)
        self.price_7.setGeometry(QtCore.QRect(0, 110, 811, 80))
        self.price_7.setMinimumSize(QtCore.QSize(811, 80))
        self.price_7.setMaximumSize(QtCore.QSize(811, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.price_7.setFont(font)
        self.price_7.setMouseTracking(True)
        self.price_7.setTabletTracking(False)
        self.price_7.setAcceptDrops(True)
        self.price_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 255);\n"
"border-top-right-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"border-bottom-right-radius: 60px;\n"
"border-bottom-left-radius: 60px;\n"
"border: 1px solid #B3B3B3;")
        self.price_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_7.setObjectName("price_7")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(270, 570, 811, 190))
        self.widget_2.setMinimumSize(QtCore.QSize(811, 190))
        self.widget_2.setMaximumSize(QtCore.QSize(811, 190))
        self.widget_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);\n"
"border-top-right-radius: 60px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.widget_2.setObjectName("widget_2")
        self.price_8 = QtWidgets.QFrame(self.widget_2)
        self.price_8.setGeometry(QtCore.QRect(0, 110, 811, 80))
        self.price_8.setMinimumSize(QtCore.QSize(811, 80))
        self.price_8.setMaximumSize(QtCore.QSize(811, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(14)
        self.price_8.setFont(font)
        self.price_8.setMouseTracking(True)
        self.price_8.setTabletTracking(False)
        self.price_8.setAcceptDrops(True)
        self.price_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 255);\n"
"border-top-right-radius: 60px;\n"
"border-top-left-radius: 60px;\n"
"border-bottom-right-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"border: 1px solid #B3B3B3;")
        self.price_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_8.setObjectName("price_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_3.setText(_translate("MainWindow", "PushButton"))
        self.button_2.setText(_translate("MainWindow", "PushButton"))
        self.button_1.setText(_translate("MainWindow", "PushButton"))
        self.button_4.setText(_translate("MainWindow", "PushButton"))
        self.button_6.setText(_translate("MainWindow", "PushButton"))
        self.button_7.setText(_translate("MainWindow", "PushButton"))
        self.button_5.setText(_translate("MainWindow", "PushButton"))
        self.button_8.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
